from fastapi import FastAPI, Request, WebSocket, WebSocketDisconnect, HTTPException, status
from fastapi.templating import Jinja2Templates
from fastapi.staticfiles import StaticFiles
from fastapi.responses import HTMLResponse
from pydantic import BaseModel
from datetime import datetime
import logging
import asyncio
import psutil


from app.database import save_metrics, get_history, cleanup_old_records, get_stats
from app.metrics import get_metrics_all


app = FastAPI()


triggers = {
	"cpu": 90,
	"memory": 90,
	"enabled": True
}

widgets = {
  "cpu": True,
  "memory": True,
  "disks": True,
  "network": True,
  "gpu": True,
  "disks_health": True,
  "disk_io": True,
  "battery": True,
 	"swap": True,
  "processes": True,
  "connections": True,
  "startup": True,
  "ports": True,
  "users": True,
  "events": True
}

pinned_pids = set()

class TriggerSettings(BaseModel):
	cpu: int = 90
	memory: int = 90
	enabled: bool = True


app.mount("/static", StaticFiles(directory="app/static"), name="static")

templates = Jinja2Templates(directory="app/templates")

logger = logging.getLogger(__name__)


@app.get("/")
def root(request: Request):
	cpu_percent = psutil.cpu_percent(interval=0.3)
	mem = psutil.virtual_memory()
	memory_total_gb = round(mem.total / 1024**3, 2)
	memory_available_gb = round(mem.available / 1024**3, 2)

	context = {
		"request": request,
		"cpu_percent": cpu_percent,
		"memory_total": memory_total_gb,
		"memory_available": memory_available_gb
	}
	
	return templates.TemplateResponse(
		request=request,
		name="index.html",
		context=context
	)


@app.get("/api/health")
def get_metrics():
	return get_metrics_all()


@app.delete("/api/process/{pid}")
def kill_process(pid: int):
	try:
		process = psutil.Process(pid)
		process.terminate()
		
		return {
			"status": "terminated",
			"pid": pid
		}
	
	except psutil.NoSuchProcess:
		raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Процесс не найден")
	except psutil.AccessDenied:
		raise HTTPException(status_code=status.HTTP_403_FORBIDDEN, detail="Нет прав на завершение процесса")


@app.get("/api/history")
def history(range: str = "hour"):
	if range == "day":
		limit = 1440
	else:
		limit = 60
	return get_history(limit=limit)


@app.get("/api/process/{pid}/info")
def process_info(pid: int):
	try:
		proc = psutil.Process(pid)

		try:
			pname = str(proc.name())
		except Exception:
			pname = "Access Denied"

		try:
			pexe = str(proc.exe())
		except Exception:
			pexe = "Access Denied"

		try:
			pstatus = str(proc.status())
		except Exception:
			pstatus = "N/A"

		try:
			puser = str(proc.username())
		except Exception:
			puser = "Access Denied"
		
		return {
			"pid": pid,
			"name": pname,
			"exe": pexe,
			"status": pstatus,
			"cpu_percent": round(proc.cpu_percent(interval=0.1) / psutil.cpu_count(), 1),
			"memory_mb": round(proc.memory_info().rss / 1024 / 1024, 2),
			"threads": proc.num_threads(),
			"create_time": datetime.fromtimestamp(proc.create_time()).isoformat(),
			"username": puser
		}
	except psutil.NoSuchProcess:
		raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Process not found")
	except psutil.AccessDenied:
		raise HTTPException(status_code=status.HTTP_403_FORBIDDEN, detail="Access denied")


@app.get("/api/export")
def export_report():
	metrics = get_metrics_all()
	now = datetime.now().strftime("%Y-%m-%d %H-%M-%S")

	html = f"""<!DOCTYPE html>
		<html>
			<head>
				<meta charset="utf-8">
				<title>System Report - {now}</title>
				<style>
					body {{ font-family: Arial, sans-serif; margin: 40px }}
					h1 {{ color: #2c3e50 }}
					table {{ border-collapse: collapse; width: 100%; margin: 20px 0 }}
					th, td {{ border: 1px solid #ddd; padding: 8px; text-align: left; }}
					th {{ background: #3498db; color: white; }}
				</style>
			</head>
			<body>
				<h1>System report - {now}</h1>
				<h2>CPU</h2>
				<p>Total: {metrics["cpu_percent"]}%</p>
				<p>Per Core: {", ".join(f"Core {i}: {load}%" for i, load in enumerate(metrics["cpu_per_core"]))}</p>
				
				<h2>Memory</h2>
				<p>Total: {metrics["memory_total"]} GB</p>
				<p>Available: {metrics["memory_available"]} GB</p>
				<p>usage: {metrics["memory_percent"]} GB</p>
				
				<h2>Disk</h2>
				<table>
					<tr><th>Device</th><th>Total (GB)</th><th>Free (GB)</th><th>Usage (GB)</th></tr>
					{"".join(f"<tr><td>{d["device"]}</td><td>{d["total"]}</td><td>{d["free"]}</td><td>{d["percent"]}</td></tr>" for d in metrics["disks"])}
				</table>
				
				<h2>Network</h2>
				<p>Sent: {metrics["net_mb_sent"]:.2f} MB</p>
				<p>Recv: {metrics["net_mb_recv"]:.2f} MB</p>
				
				<h2>Top Processes</h2>
				<table>
					<tr><th>PID</th><th>Name</th><th>CPU%</th><th>Threads</th></tr>
					{"".join(f"<tr><td>{p["pid"]}</td><td>{p["name"]}</td><td>{p["cpu_percent"]}</td><td>{p["threads"]}</td></tr>" for p in metrics["top_processes"])}
				</table>
				
				<p><em>Generated by System Monitoring</em></p>
			</body>
		</html>"""

	return HTMLResponse(content=html, headers={
		"Content-Disposition": f"attachment; filename=system_report_{datetime.now().strftime('%Y%m%d_%H%M%S')}.html"
	})


@app.get("/api/triggers")
def get_triggers():
	return triggers


@app.put("/api/triggers")
def update_triggers(settings: TriggerSettings):
	triggers["cpu"] = settings.cpu
	triggers["memory"] = settings.memory
	triggers["enabled"] = settings.enabled

	return triggers


@app.get("/api/widgets")
def get_widgets():
	return widgets


@app.put("/api/widgets")
def update_widgets(settings: dict):
	widgets.update(settings)

	return widgets


@app.get("/api/stats")
def get_stats_data(range: str = "hour"):
	return get_stats(range)
	

@app.websocket("/ws/metrics")
async def websocket_metrics(websocket: WebSocket):
	await websocket.accept()
	last_save_time = datetime.now()
	last_cleanup_time = datetime.now()
	
	try:
		while True:
			content = get_metrics()

			content["alert_cpu"] = False
			content["alert_memory"] = False
			content["cpu_threshold"] = triggers["cpu"]
			content["memory_threshold"] = triggers["memory"]

			if triggers["enabled"]:
				if content["cpu_percent"] > triggers["cpu"]:
					content["alert_cpu"] = True
					logger.warning(f"CPU threshold exceeded: {content["cpu_percent"]}% > {triggers["cpu"]}%")

				if content["memory_percent"] > triggers["memory"]:
					content["alert_memory"] = True
					logger.warning(f"Memory threshold exceeded: {content["memory_percent"]}% > {triggers["memory"]}%")

			if (datetime.now() - last_cleanup_time).seconds >= 3600:
				cleanup_old_records()
				last_cleanup_time = datetime.now()

			if (datetime.now() - last_save_time).seconds >= 60:
				save_metrics(content)
				last_save_time = datetime.now()
		
			await websocket.send_json(content)
		
			await asyncio.sleep(1)
	except WebSocketDisconnect as e:
		logger.info("Пользователь отключился.")
